added HW_4 of SQL
VitaliySokoliuk/MySql_HomeWorks pull request #4
Opened 2020-02-25 14:29 UTC by VitaliySokoliuk

2020-02-25 14:30 UTC, VitaliySokoliuk commented
check, please

2020-02-25 21:04 UTC, vtymtsiv requested changes
Заповни кожну таблицю по декілька записів.
Діаграми прикріпи у описі у вигляді скріншоту.

2020-02-25 21:04 UTC, VolodymyrTymtsiv commented on sql_4/HW_Sql_4_Tast_2.sql
> +        Пошта varchar(30)
Виглядає не дуже)) Давай краще англійською привикати)))

2020-02-26 13:09 UTC, VitaliySokoliuk commented
I fix all your remark

2020-02-28 13:04 UTC, vtymtsiv approved these changes
Looks good!

2020-03-01 16:06 UTC, merged